name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  merge_group:

jobs:
  check-backend-or-frontend:
    name: Check Backend or Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend == 'true' }}
      backend: ${{ steps.filter.outputs.backend == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/
            frontend/
            backend/

      - name: Check backend or frontend
        id: filter
        uses: ./.github/actions/path-filter

  frontend-test:
    name: Frontend Test
    runs-on: ubuntu-latest
    needs: check-backend-or-frontend
    if: ${{ needs.check-backend-or-frontend.outputs.frontend == 'true' }}
    steps:
      - name: Good
        run: |
          echo "Good"
          sleep 60
          exit 0

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    needs: check-backend-or-frontend
    if: ${{ needs.check-backend-or-frontend.outputs.backend == 'true' }}
    steps:
      - name: Good
        run: |
          echo "Good"
          sleep 120
          exit 0

  run-always:
    name: Run Always
    runs-on: ubuntu-latest
    steps:
      - name: Always
        run: |
          echo "Always"
          exit 0
